SystemDiskSize: 40
RuntimeType: Container
ServiceType: private
ArtifactSourceType: DockerCompose
ServiceBuildRegion: ap-southeast-1
RepoName: workhardliuzheng/computenest-quickstart-asktable
DockerComposeEnvPath: .env
RegionId: cn-hangzhou
DockerComposeYamlPath: docker-compose.yml
Owner: workhardliuzheng
Branch: main
Platform: github
